use regex::Regex;

/// Please run it first
fn generate_regex() {
    let emoji_file = include_str!("emoji.txt");
    let emoji_regex = Regex::new(r"; [a-zA-Z- ]*# ([^E]+)E\d").unwrap();
    let emojis = emoji_regex.captures_iter(emoji_file).collect::<Vec<_>>();
    let mut valid_emojis = "[\n".to_string();
    for emoji in emojis {
        let emoji = emoji.get(1).unwrap().as_str();
        valid_emojis.push_str(emoji);
    }
    valid_emojis.push_str("\n]");
    let valid_emojis = valid_emojis.replace(' ', "");
    let valid_chars = include!("valid_chars.txt");

    let mut file = std::fs::File::create("regex.txt").unwrap();
    let regex = format!("/* generated by build.rs */\nr\"^({}|{})+$\"", valid_chars, valid_emojis);
    std::io::Write::write_all(&mut file, regex.as_bytes()).unwrap();
}

fn main(){
    generate_regex();
}