[package]
name = "domain_filter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
regex = "1.6"


[dependencies]
regex = "1.6"
lazy_static = "1.4"